### ISSUE TITLE
yaml adjustment to compile on git

### ISSUE THREAD

**Issue by tudstudent** [yoziru/esphome-zehnder-comfoair#2]
You might want to change the yaml to:

```
external_components:
  - source: github://yoziru/esphome-zehnder-comfoair
    components: [ zehnder_comfoair_q ]
```

This way the build will be done in ESPhome. Easier for unexperienced users (instead of make etc).

**Comment by yoziru** [comment]
This should work now with the added `dashboard_import` (https://github.com/yoziru/esphome-zehnder-comfoair/commit/33ddeb505e90f30e0e31d68ea02cd973874bf494)
